# Generated by Django 3.1.6 on 2021-03-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='Description',
            field=models.TextField(),
        ),
    ]
